### ISSUE TITLE
Regarding Categaory

### ISSUE THREAD

**Issue by palwencha** [gwin/wpadverts#1]
Hi ,
I am unable to see Categaory in free plugin that is provided.

**Comment by gwin** [comment]
Hi, i am not sure what do you exactly mean? Can't you see them in wp-admin or in the frontend?

**Comment by palwencha** [comment]
Yes, I am not able to see in frontend all the categories that I have added. Can please let me know about this

**Comment by gwin** [comment]
Can you link to a page where you have this problem?

Also this does not seem like a bug, you should rather ask your question on support forum https://wordpress.org/support/plugin/wpadverts

**Comment by palwencha** [comment]
Please find the below link:
https://php4-foodcrazzy.rhcloud.com/adverts/?_sm_au_=i2sTWFvfSmRQsTHP

on the above link when you click you won't find the categories.

**Comment by gwin** [comment]
It should look like this by default after installation, if you want to display categories you need to create a new page from wp-admin / Pages panel (or use one of existing pages) and in the page content put [adverts_categories] shortcode http://wpadverts.com/documentation/displaying-categories-adverts_categories/
